### ISSUE TITLE
Opiskelija voi valita palaute-frekvenssin

### ISSUE THREAD

**Issue by vilkiida** [tmc-coach/tmc-coach#172]
Käyttäjä voi valita kuinka monta checkpointia on ennen deadlinea

**Comment by tuukkalai** [comment]
Muutamia ideoita:
- Kalenterinäkymän alle vois lisätä ennen "Set deadline" -painiketta kentän, johon lisätään haluttujen checkpointien määrä
- Huomioitavaa on datan validointi ja checkpointien määrän rajoittaminen (esim. 1-10?)
- Voisiko checkpointien määrän rajoittaa nykyisen päivämäärän, valitun deadlinen ja nykyisen suoritusasteen mukaan?
- Voisiko käyttäjä valita esim. "Haluan asettaa checkpointit asettumaan viikoittain/kuukausittain"?

**Comment by tuukkalai** [comment]
- [ ] #206
