### ISSUE TITLE
Pohtimista e2e-testien ajamisen tiheyteen

### ISSUE THREAD

**Issue by minervaana** [tmc-coach/tmc-coach#175]
"E2E testien ajaminen tuskastuttaa, koska ne kestää niin kauan."

**Comment by tuukkalai** [comment]
Testien ajaminen mahdollisimman usein on kannattavaa, jotta havaitaan ajoissa mahdolliset virheet uusia toiminnallisuuksia kehitettäessä.

Testien nopeuttaminen vaatisi seuraavaksi TMC-APIn mockaamista.
