### ISSUE TITLE
Lähetettävien sähköpostien kirjoittaminen

### ISSUE THREAD

**Issue by minervaana** [tmc-coach/tmc-coach#178]
Checkpointtien kohdalla lähetettävien viestien suunnittelu
Tehtyjen tehtävien määrä yms.
- Omat kannustusviestit 25%, 50% ja 75% checkpointeille, jos jäljessä aikataulusta
- Omat onnistumisviestit 25%, 50% ja 75% checkpointeille, jos pysynyt aikataulussa

**Comment by tikuisma** [comment]
Luonnostelua geneeriselle onnistumisviestille:

TMC Coach has news for you (Joku slogan alkuun)

=================================================================

Congrats from your { first, second or third } milestone in { kurssin nimi } course! You have earned and been awarded with { kurssin pisteprosentti } % points from your scheduled course on time.

TMC Coach also told us that you are ahead of your schedule by { päivien lkm }. Thats awesome! <-- Voisi printata, jos esim. 1 päivän tai enemmän aikataulua edellä?

You have made such a good work, so TMC Coach encourages you to keep up that good work and continue to collect more points from the course!

=================================================================

{ slogan tms. }

**Comment by tikuisma** [comment]
Luonnostelua geneeriselle kannustusviestille:

Emailin otsikko: TMC Coach ........

TMC Coach has news for you (Joku slogan alkuun)

=================================================================

TMC Coach has informed us that you are little behind on your schedule in { kurssin nimi } course. So far you have earned and been awarded with { kurssin pisteprosentti } % points from the course.

TMC Coach encourages you to continue the course doing exercises step by step. You can do this!

Whenever you are feeling too overwhelmed, you can change your schedule for the course in TMC Coach -application.

=================================================================

{ slogan tms. }
