### ISSUE TITLE
Deadlinen kuukausittainen asetus ei toimi oikein

### ISSUE THREAD

**Issue by tikuisma** [tmc-coach/tmc-coach#221]
Kuva kertoo tarkemmin, mutta en saa asetettua deadlinea elokuulle, koska sovellus ilmoittaa ettei kuukausittaiset checkpointit saa olla yli 2 vuoden päässä?

![Image](https://user-images.githubusercontent.com/93583969/232012427-e2ba6032-4fc0-4b6d-8cd0-3940dd0ad7f9.png)

**Comment by suuranna** [comment]
Siellä Deadlines.js-tiedostossa näyttää olevan rivillä 51 <-merkki vaikka pitäis olla <-merkki :DDD
eli
if (freqvency === 2 && days_between < 720) {
pitäis olla
if (freqvency === 2 && days_between > 720) {

**Comment by tikuisma** [comment]
no se oli nopee :grin:
