### ISSUE TITLE
README standardin mukaiseksi

### ISSUE THREAD

**Issue by AnonymousHobbit** [tmc-coach/tmc-coach#8]
Liittyy user storyyn #11

**Comment by tuukkalai** [comment]
Readme sisältää nyt hyvin tähän mennessä tehtyä dokumentaatiota ja esittelyä sovelluksesta ja projektista.
Readme ja dokumentaatio taitaa olla on-going tehtäviä, jotka ovat "valmiita" vasta kun tiimiläisillä on arvosana Sisussa.
